security:
    encoders:
        Symfony\Component\Security\Core\User\User: SHA1
        Symwow\Bundles\DefaultBundle\Entity\Account: SHA1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
