AccountBanned:
    type: entity
    table: account_banned
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
        bandate:
            id: true
            type: integer
            unsigned: true
            nullable: false
        unbandate:
            type: integer
            unsigned: true
            nullable: false
        bannedby:
            type: string
            length: 50
            fixed: false
            nullable: false
        banreason:
            type: string
            length: 255
            fixed: false
            nullable: false
        active:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
