Autobroadcast:
    type: entity
    table: autobroadcast
    fields:
        id:
            id: true
            type: boolean
            nullable: false
        realmid:
            id: true
            type: integer
            unsigned: false
            nullable: false
        weight:
            type: boolean
            nullable: true
        text:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
