Ip2nation:
    type: entity
    table: ip2nation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        ip:
            type: integer
            unsigned: true
            nullable: false
        country:
            type: string
            length: 2
            fixed: true
            nullable: false
    lifecycleCallbacks: {  }
