Logs:
    type: entity
    table: logs
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        time:
            type: integer
            unsigned: true
            nullable: false
        realm:
            type: integer
            unsigned: true
            nullable: false
        type:
            type: boolean
            nullable: false
        level:
            type: boolean
            nullable: false
        string:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
