RbacPermissions:
    type: entity
    table: rbac_permissions
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
    manyToMany:
        linkedid:
            targetEntity: RbacPermissions
            cascade: {  }
            mappedBy: null
            inversedBy: id
            joinTable:
                name: rbac_linked_permissions
                joinColumns:
                    -
                        name: id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: linkedId
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
