Realmcharacters:
    type: entity
    table: realmcharacters
    fields:
        realmid:
            id: true
            type: integer
            unsigned: true
            nullable: false
        acctid:
            id: true
            type: integer
            unsigned: true
            nullable: false
        numchars:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
