Realmlist:
    type: entity
    table: realmlist
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 32
            fixed: false
            nullable: false
        address:
            type: string
            length: 255
            fixed: false
            nullable: false
        localaddress:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: localAddress
        localsubnetmask:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: localSubnetMask
        port:
            type: smallint
            nullable: false
        icon:
            type: boolean
            nullable: false
        flag:
            type: boolean
            nullable: false
        timezone:
            type: boolean
            nullable: false
        allowedsecuritylevel:
            type: boolean
            nullable: false
            column: allowedSecurityLevel
        population:
            type: float
            nullable: false
        gamebuild:
            type: integer
            unsigned: true
            nullable: false
    lifecycleCallbacks: {  }
